#!/usr/bin/env python

import sys
import smtplib

from email.mime.text import MIMEText
from subprocess import Popen
from subprocess import PIPE

'''
send the mail to developers after the master branch has been updated by admin
'''

receivers = ['userA@a.com', 'userB@b.com'] #recepients
sender = 'someone@somehost' #need to be a valid one

lastRev = Popen("git log --pretty=format:'%H' -1 --skip=1 --author=Admin --merges", stdout=PIPE, shell=True).communicate()[0]

diff = Popen("git diff --stat HEAD.." + lastRev, stdout=PIPE, shell=True).communicate()[0]

msg = MIMEText('Master branch just updated \n\nList of files been modified:\n\n %(content)s' % {'content':diff})
msg['Subject'] = '[REPO ALERT] Master branch just updated'
msg['From'] = sender
msg['To'] = receiver

server = smtplib.SMTP('localhost')
server.sendmail(sender, receivers, msg.as_string())
server.quit()

sys.exit(0)